/*
    Created on : 22 jul. 2022, 20:19:49
    Author     : Miguel Londono, Nicolas Diaz, Daniel Paez
    Project: Proyecto Final de Modelos de Programacion I
 */
package vista;

import modelo.MdlCalificarPelicula;
import control.logica.CtrCalificarPelicula;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 * 
 * @author Miguel Londono
 * @author Daniel Paez
 * @author Nicolas Di­az
 */
public class VtnCalificarPelicula extends javax.swing.JFrame {

    private final MdlCalificarPelicula mdlCalificar;
    private CtrCalificarPelicula ctrCalificar;

    public VtnCalificarPelicula(MdlCalificarPelicula modelo) {
        this.mdlCalificar = modelo;
        initComponents();
        setLocationRelativeTo(null);

        // configura el spinner de calificacion
        SpinnerNumberModel model1 = new SpinnerNumberModel(1, 1, 5, 1);
        spCalificacion.setModel(model1);

        capturarEventos();
    }

    /**
     *
     * @return
     */
    public CtrCalificarPelicula getCtrCalificar() {
        if (ctrCalificar == null) {
            ctrCalificar = new CtrCalificarPelicula(this);
        }
        return ctrCalificar;
    }

    /**
     * 
     */
    private void capturarEventos() {
        btnVolverAMenu.addActionListener(getCtrCalificar());
        btnCalificar.addActionListener(getCtrCalificar());
    }

    public MdlCalificarPelicula getMdlCalificar() {
        return mdlCalificar;
    }

    public JComboBox getCombobox() {
        return cbPeliculas;
    }

    public JButton getBoton() {
        return btnVolverAMenu;
    }

    public JButton getBotonCalificar() {
        return btnCalificar;
    }

    public JSpinner getSpinner() {
        return spCalificacion;
    }

    public void volverMenu() {
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spCalificacion = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        btnCalificar = new javax.swing.JButton();
        cbPeliculas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnVolverAMenu = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Cine Distrital");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 220, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/palomitas-de-maiz.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 100));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 80, 87));
        jLabel8.setText("Menu Cliente");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/clasificacion (1).png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 80, 80));

        spCalificacion.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel2.add(spCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 80, 50));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Calificacion");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        btnCalificar.setBackground(new java.awt.Color(204, 255, 255));
        btnCalificar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        btnCalificar.setForeground(new java.awt.Color(94, 174, 253));
        btnCalificar.setText("Calificar");
        btnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 220, 60));

        cbPeliculas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        cbPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPeliculasActionPerformed(evt);
            }
        });
        jPanel2.add(cbPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 340, 50));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Pelicula");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, 40));

        btnVolverAMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnVolverAMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        btnVolverAMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAMenu.setText("Volver al menu");
        btnVolverAMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAMenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolverAMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 200, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar-sesion (1).png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 80, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 740, 510));

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img3/Ellipse 209.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img3/Union.png"))); // NOI18N
        jLabel4.setText("re");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPeliculasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbPeliculasActionPerformed

    private void btnVolverAMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverAMenuActionPerformed

    private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalificarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificar;
    private javax.swing.JButton btnVolverAMenu;
    private javax.swing.JComboBox<String> cbPeliculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner spCalificacion;
    // End of variables declaration//GEN-END:variables
}
