/*
    Created on : 22 jul. 2022, 20:19:49
    Author     : Miguel Londono, Nicolas Diaz, Daniel Paez
    Project: Proyecto Final de Modelos de Programacion I
 */
package vista;

import modelo.MdlRegistroEmpleado;
import modelo.MdlInicioSesion;
import modelo.MdlCambioCargoEmpleado;
import modelo.MdlVerEmpleado;
import javax.swing.JOptionPane;

/**
 * 
 * @author Miguel Londono
 * @author Daniel Paez
 * @author Nicolas Di­az
 */
public class VtnMenuAdmin extends javax.swing.JFrame {

    
    private VtnRegistroEmpleado vtnRegistro;
    
    public VtnMenuAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAnadir = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnCambiarCargo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 200, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Cine Distrital");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 220, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/palomitas-de-maiz.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 100));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Avatar_Container.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 110, 70));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 80, 87));
        jLabel8.setText("Menu Administrador");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar-sesion (1).png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 80, 80));

        btnAnadir.setBackground(new java.awt.Color(204, 255, 255));
        btnAnadir.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        btnAnadir.setForeground(new java.awt.Color(94, 174, 253));
        btnAnadir.setText("Añadir Empleados");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 230, 50));

        btnEmpleados.setBackground(new java.awt.Color(204, 255, 255));
        btnEmpleados.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(94, 174, 253));
        btnEmpleados.setText("Empleados");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 230, 50));

        btnCambiarCargo.setBackground(new java.awt.Color(204, 255, 255));
        btnCambiarCargo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        btnCambiarCargo.setForeground(new java.awt.Color(94, 174, 253));
        btnCambiarCargo.setText("Cambiar Cargo ");
        btnCambiarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarCargoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCambiarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 230, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 740, 510));

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img3/Ellipse 209.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img3/Union.png"))); // NOI18N
        jLabel3.setText("re");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        MdlRegistroEmpleado mdlRegistro;
        mdlRegistro = new MdlRegistroEmpleado();
        mdlRegistro.Iniciar();
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnCambiarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarCargoActionPerformed
        MdlCambioCargoEmpleado mdlCambiarCargo;
        mdlCambiarCargo = new MdlCambioCargoEmpleado();
        mdlCambiarCargo.Iniciar();
    }//GEN-LAST:event_btnCambiarCargoActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        MdlVerEmpleado mdlVerEmpleado;
        mdlVerEmpleado = new MdlVerEmpleado();
        mdlVerEmpleado.iniciar();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MdlInicioSesion mdlInicioSesion;
        mdlInicioSesion = new MdlInicioSesion();
        mdlInicioSesion.iniciar();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnCambiarCargo;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
