/*
    Created on : 22 jul. 2022, 20:19:49
    Author     : Miguel Londono, Nicolas Diaz, Daniel Paez
    Project: Proyecto Final de Modelos de Programacion I
 */
package vista;

import modelo.MdlReciboSnacks;
import control.logica.CtrReciboSnacks;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 * 
 * @author Miguel Londono
 * @author Daniel Paez
 * @author Nicolas Di­az
 */
public class VtnReciboSnacks extends javax.swing.JFrame {

    int espacio;

    private final MdlReciboSnacks mdlReciboSnacks;
    private CtrReciboSnacks ctrReciboSnacks;

    /**
     *
     * @param modelo
     */
    public VtnReciboSnacks(MdlReciboSnacks modelo) {
        this.mdlReciboSnacks = modelo;
        initComponents();
        setLocationRelativeTo(null);
        capturarEventos();
    }

    /**
     * 
     * @return 
     */
    public CtrReciboSnacks getCtrReciboSnacks() {
        if (ctrReciboSnacks == null) {
            ctrReciboSnacks = new CtrReciboSnacks(this);
        }
        return ctrReciboSnacks;
    }

    /**
     * 
     */
    public void capturarEventos() {
        btnPagar.addActionListener(getCtrReciboSnacks());
    }

    JLabel[] espacios = new JLabel[6];

    public JLabel[] getEspacios() {
        espacios[0] = espacio1;
        espacios[1] = espacio2;
        espacios[2] = espacio3;
        espacios[3] = espacio4;
        espacios[4] = espacio5;
        espacios[5] = espacio6;
        return espacios;
    }

    public MdlReciboSnacks getMdlReciboSnacks() {
        return mdlReciboSnacks;
    }

    public JLabel getPrecio() {
        return jLabel5;
    }

    public JButton pagar() {
        return btnPagar;
    }

    public void mostrarMenu() {
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        espacio6 = new javax.swing.JLabel();
        espacio5 = new javax.swing.JLabel();
        espacio4 = new javax.swing.JLabel();
        espacio3 = new javax.swing.JLabel();
        espacio2 = new javax.swing.JLabel();
        espacio1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("Cine Distrital");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 220, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/palomitas-de-maiz.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 100));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/impuesto.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 80, 80));

        btnPagar.setBackground(new java.awt.Color(204, 255, 255));
        btnPagar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(94, 174, 253));
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel2.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, 60));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Recibo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/recibir-cantidad.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 80, 80));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Valor a pagar: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 300, 36));

        espacio6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        espacio6.setText("Valor a pagar: ");
        jPanel2.add(espacio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 280, 36));

        espacio5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        espacio5.setText("Pelicula:");
        jPanel2.add(espacio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 280, 36));

        espacio4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        espacio4.setText("Hora:");
        jPanel2.add(espacio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 260, 36));

        espacio3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        espacio3.setText("Fecha:");
        jPanel2.add(espacio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 260, 36));

        espacio2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        espacio2.setText("Sala:");
        jPanel2.add(espacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 280, 36));

        espacio1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        espacio1.setText("Hot:");
        jPanel2.add(espacio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 250, 36));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 740, 510));

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img3/Ellipse 209.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img3/Union.png"))); // NOI18N
        jLabel14.setText("re");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed

    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel espacio1;
    private javax.swing.JLabel espacio2;
    private javax.swing.JLabel espacio3;
    private javax.swing.JLabel espacio4;
    private javax.swing.JLabel espacio5;
    private javax.swing.JLabel espacio6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
